### ISSUE TITLE
While submitting, if user moves between screens, the submit cancels.

### ISSUE THREAD

**Issue by srivadi** [CoVital-Project/covital_calibration_app#31]
Does the the upload cancel, if the user was to move from the window Review and submit to the previous screen, Medical History and Status? But if I exist the application and come back, it shows that it is submitting. But if I move between screens, the submitting disappears. What is the expected behavior and do we need to have a warning pop up window, if the submit cancels?

**Comment by MalcolmMielle** [comment]
The submit should not be cancelled. If you submit the info then it's done. The user is not expecting the move away from the finding screen until the upload is done.

Sadly fixing the behavior for this issue would take too long so I won't do it :/.

**Comment by MalcolmMielle** [comment]
I can't confirm this behavior in Android. If I change screens, the upload is successful because it's sent in the background. I think it's because you might have been using an old version of the app and the upload just stopped working.

I'll close and reopen the issue if you see this behavior in the latest version of the app.
